AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'doc/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  Max: 121
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/NumericLiteralPrefix:
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Exclude:
    - 'app/serializers/*'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 56

Metrics/ClassLength:
  Max: 256

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 70

Metrics/PerceivedComplexity:
  Max: 13
