name: Rspec
on: [pull_request]

jobs:
  verify:
    name: Rspec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install

      - name: Build database
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
            bin/rails db:setup

      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
